// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmlpghrncrblwbvoupxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbHBnaHJuY3JibHdidm91cHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDUyOTQsImV4cCI6MjA1NzY4MTI5NH0.QUuN-2CgYsWRt75jP3UWRpzJOXmNridtHiKQ8ftqOxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);